name: Publish Packages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-package-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Authenticate with GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=\${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

      - name: Install Dependencies
        run: npm ci

      - name: Publish Package 1
        run: npm publish --access public --tag latest --prefix ./src/utility-1

  publish-package-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Authenticate with GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=\${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

      - name: Install Dependencies
        run: npm ci

      - name: Publish Package 2
        run: npm publish --access public --tag latest --prefix ./src/utility-2
